"""generates the 'iw.db' and 'rdns.db' files to be consumed by BIND"""

import argparse
import datetime
import ipaddress
import os
import re
import sys
from pathlib import Path

from rpsl import DATA_DIR, TLD, Registry, closest_domain

HEADER = """; This file was autogenerated by utils/generate_zone.py
; Do not edit! It will be regenerated.
$ORIGIN {origin}
$TTL 1h
@ IN SOA v.root-servers.iw. contact.itsvic.dev. {serial} 1h 15m 4d 30m

"""
SERIAL_RE = re.compile(r"^@ IN SOA \S+ \S+ (\d+) ", re.MULTILINE)
RDNS_NET = ipaddress.IPv4Network("10.0.0.0/8")


def forward_records(registry: Registry) -> list[str]:
    domains = registry.valid("dns")
    delegations, ds_records, glue = set(), set(), {}
    for domain, obj in domains.items():
        for nserver in obj.get_all("nserver"):
            host, addr = nserver.split()
            delegations.add((domain, host))
            if closest_domain(domains, host) == domain:
                glue.setdefault(host, set()).add(ipaddress.ip_address(addr))

        # iw. has no parent zone, so its ds-rdata is documentation only
        if domain != TLD:
            ds_records.update((domain, rdata) for rdata in obj.get_all("ds-rdata"))

    records = [f"{domain}. IN NS {host}." for domain, host in sorted(delegations)]
    records += [f"{domain}. IN DS {rdata}" for domain, rdata in sorted(ds_records)]
    records.append("")
    for host in sorted(glue):
        for addr in sorted(glue[host], key=lambda a: (a.version, a)):
            records.append(f"{host}. IN {'A' if addr.version == 4 else 'AAAA'} {addr}")
    return records


def reverse_records(registry: Registry, problems: list[str]) -> list[str]:
    delegations = set()
    for name, obj in registry.valid("inetnum").items():
        nservers = obj.get_all("nserver")
        if not nservers:
            continue
        network = ipaddress.IPv4Network(obj.get("cidr"))
        if network.prefixlen != 24 or not network.subnet_of(RDNS_NET):
            problems.append(f"inetnum/{name}: reverse DNS is only delegated for /24s in {RDNS_NET}")
            continue
        delegations.update((network, host) for host in nservers)

    apex = registry.valid("dns").get(TLD)
    records = [f"@ IN NS {nserver.split()[0]}." for nserver in sorted(apex.get_all("nserver") if apex else [])]
    for network, host in sorted(delegations):
        name = ".".join(reversed(str(network.network_address).split(".")[1:3]))
        records.append(f"{name} IN NS {host}.")
    return records


def render(origin: str, serial: int, records: list[str]) -> str:
    return HEADER.format(origin=origin, serial=serial) + "".join(f"{r}\n" for r in records)


def write_zone(path: Path, origin: str, records: list[str]) -> bool:
    old = path.read_text() if path.exists() else ""
    match = SERIAL_RE.search(old)
    old_serial = int(match[1]) if match else 0
    if render(origin, old_serial, records) == old:
        return False

    today = int(datetime.date.today().strftime("%Y%m%d00"))
    tmp = path.with_name(f"{path.name}.tmp")
    tmp.write_text(render(origin, max(old_serial + 1, today), records))
    os.replace(tmp, path)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit non-zero on any warning")
    parser.add_argument("--data", type=Path, default=DATA_DIR, help="registry data directory")
    args = parser.parse_args()

    registry = Registry(args.data)
    for kind in ("dns", "inetnum"):
        if kind not in registry.schemas:
            print(f"error: no valid schema for {kind}, refusing to write zones", file=sys.stderr)
            return 1

    problems = [
        f"{problem.path.parent.name}/{problem.path.name}: {problem.message}"
        for problem in registry.validate()
        if problem.error and problem.path.parent.name in ("dns", "inetnum")
    ]
    forward = forward_records(registry)
    reverse = reverse_records(registry, problems)
    for problem in problems:
        print(f"warning: {problem}", file=sys.stderr)

    for path, origin, records in (
        (Path("iw.db"), "iw.", forward),
        (Path("rdns.db"), "10.in-addr.arpa.", reverse),
    ):
        changed = write_zone(path, origin, records)
        print(f"{path}: {'updated' if changed else 'unchanged'}")
    return 1 if args.check and problems else 0


if __name__ == "__main__":
    sys.exit(main())
