"""generates the 'iw.db' file to be consumed by BIND"""

import glob
import os
import pickle

from dumbschema import dumb_parse_object

serial = 1

if os.path.exists(".serial"):
    with open(".serial", "rb") as file:
        serial = pickle.load(file)

HEADER = f"""; This file was autogenerated by utils/generate_zone.py
; Do not edit! It will be regenerated.
$ORIGIN iw.
$TTL 1h
@ IN SOA iw. contact.itsvic.dev. {serial} 1h 15m 4d 30m
"""

domains = set()
nameservers = set()

for file in glob.iglob("data/dns/*"):
    with open(file) as f:
        obj = dumb_parse_object(f.read())
    nservers = obj["nserver"]
    domain = obj["domain"]
    if nservers is not list:  # single nserver defined
        nservers = [nservers]

    for nserver in nservers:
        ns, a = [i.strip() for i in nserver.split(" ", 1)]  # pyright: ignore[reportAttributeAccessIssue]
        domains.add((domain, ns))
        nameservers.add((ns, a))

with open("iw.db", "w+") as file:
    file.write(HEADER + "\n")
    for domain, ns in sorted(list(domains)):
        file.write(f"{domain}. IN NS {ns}\n")
    file.write("\n")
    for ns, a in sorted(list(nameservers)):
        file.write(f"{ns}. IN A {a}\n")

with open(".serial", "wb+") as file:
    pickle.dump(serial + 1, file)
