"""generates the 'iw.db' file to be consumed by BIND"""

import glob
import ipaddress
import os
import pickle

from dumbschema import dumb_parse_object

serial = 1
old_domains = set()
old_nameservers = set()
old_rdns = set()
old_ds_records = set()

if os.path.exists(".zone-data"):
    with open(".zone-data", "rb") as file:
        data = pickle.load(file)
        if len(data) == 3:
            serial, old_domains, old_nameservers = data
        elif len(data) == 4:
            serial, old_domains, old_nameservers, old_rdns = data
        elif len(data) == 5:
            serial, old_domains, old_nameservers, old_rdns, old_ds_records = data
        else:
            raise Exception("Old data has unexpected number of items")


def HEADER(origin):
    return f"""; This file was autogenerated by utils/generate_zone.py
; Do not edit! It will be regenerated.
$ORIGIN {origin}
$TTL 1h
@ IN SOA v.root-servers.iw. contact.itsvic.dev. {serial} 1h 15m 4d 30m
"""


domains = set()
nameservers = set()
rdns = set()
ds_records = set()

for file in glob.iglob("data/dns/*"):
    with open(file) as f:
        obj = dumb_parse_object(f.read())
    nservers = obj["nserver"]
    domain = obj["domain"]
    if type(nservers) is not list:  # single nserver defined
        nservers = [nservers]

    for nserver in nservers:
        ns, a = [i.strip() for i in nserver.split(" ", 1)]  # pyright: ignore[reportAttributeAccessIssue]
        domains.add((domain, ns))
        nameservers.add((ns, a))

    # iw. itself has no parent zone to publish its own DS in, so its
    # ds-rdata is documentation only and must not be served from iw.db.
    if domain != "iw":
        ds_rdata = obj.get("ds-rdata", [])
        if type(ds_rdata) is not list:
            ds_rdata = [ds_rdata]
        for rdata in ds_rdata:
            ds_records.add((domain, rdata))

# only scan for /24s
for file in glob.iglob("data/inetnum/*_24"):
    with open(file) as f:
        obj = dumb_parse_object(f.read())
    nservers = obj.get("nserver")
    ip = str(ipaddress.ip_network(obj["cidr"]).network_address)  # pyright: ignore[reportArgumentType]
    if nservers is None:
        continue

    if type(nservers) is not list:  # single nserver defined
        nservers = [nservers]

    for nserver in nservers:
        rdns.add((ip, nserver))

if (
    domains == old_domains
    and nameservers == old_nameservers
    and rdns == old_rdns
    and ds_records == old_ds_records
):
    print("Domains are identical, skipping update")
    exit()

with open("iw.db", "w+") as file:
    file.write(HEADER("iw.") + "\n")
    for domain, ns in sorted(list(domains)):
        file.write(f"{domain}. IN NS {ns}.\n")
    for domain, rdata in sorted(list(ds_records)):
        file.write(f"{domain}. IN DS {rdata}\n")
    file.write("\n")
    for ns, a in sorted(list(nameservers)):
        file.write(f"{ns}. IN A {a}\n")

# only populate /24 ranges
with open("rdns.db", "w+") as file:
    file.write(HEADER("10.in-addr.arpa.") + "\n")
    iw_ns = [ns for domain, ns in domains if domain == "iw"]
    for domain, ns in sorted([d for d in domains if d[0] == "iw"]):
        file.write(f"@ IN NS {ns}.\n")
    for ip, ns in sorted(list(rdns)):
        # chop off first and last octets, reverse them
        ip_domain = ".".join(reversed(ip.split(".")[1:3]))
        file.write(f"{ip_domain} IN NS {ns}.\n")

with open(".zone-data", "wb+") as file:
    pickle.dump((serial + 1, domains, nameservers, rdns, ds_records), file)
